# Generated by Django 5.0.4 on 2024-04-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secureFlowMain', '0002_appointment_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_id',
            field=models.CharField(max_length=256),
        ),
    ]
