# Generated by Django 5.0.4 on 2024-04-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_auto_20210518_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Doctor'), (3, 'Patient'), (4, 'Receptionist'), (5, 'Pharmacy')]),
        ),
    ]
