# Generated by Django 3.0.5 on 2024-05-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0019_hospital_pharmacy_prescription_receptionist'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hospitalId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitalId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='hospitalId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
