# Generated by Django 3.0.5 on 2024-05-23 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0020_auto_20240523_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='hospitalname',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
