# Generated by Django 3.0.5 on 2024-05-25 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_appointment_hospitalname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='hospital',
        ),
    ]
