# Generated by Django 3.0.5 on 2024-05-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pic/AdminProfilePic/'),
        ),
    ]
