# Generated by Django 3.0.5 on 2024-05-26 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20240526_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='assignedDoctorId',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='assignedDoctorName',
        ),
    ]
