# Generated by Django 3.0.5 on 2024-05-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_auto_20240526_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='daySpent',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='roomCharge',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctorId',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patientId',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patientName',
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='appointmentId',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='hospital.Appointment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='admitDate',
            field=models.DateField(),
        ),
    ]
