# Generated by Django 3.0.5 on 2024-05-26 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0028_auto_20240526_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='admitDate',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='status',
        ),
        migrations.AddField(
            model_name='appointment',
            name='diagnosis',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='treatment',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PatientDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitDate', models.DateField(auto_now=True)),
                ('height', models.FloatField(null=True)),
                ('weight', models.FloatField(null=True)),
                ('blood_pressure', models.CharField(max_length=10, null=True)),
                ('cholesterol', models.FloatField(null=True)),
                ('blood_sugar', models.FloatField(null=True)),
                ('heart_rate', models.FloatField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('symptoms', models.TextField(max_length=500)),
                ('diagnosis', models.TextField(max_length=500)),
                ('treatment', models.TextField(max_length=500)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hospital.Patient')),
            ],
        ),
    ]
