# Generated by Django 3.0.5 on 2024-05-26 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0030_auto_20240526_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='hospitalname',
            new_name='hospitalName',
        ),
        migrations.CreateModel(
            name='PharmacyMedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineName', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False)),
                ('pharmacyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital.Pharmacy')),
            ],
        ),
    ]
