# Generated by Django 3.0.5 on 2024-05-27 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0031_auto_20240527_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Registered', 'Registered'), ('Checked in', 'Checked in'), ('Issued', 'Issued'), ('Ready', 'Ready'), ('Dispensed', 'Dispensed'), ('Medication Active', 'Medication Active'), ('Complete', 'Completed')], default='Scheduled', max_length=20),
        ),
    ]
