# Generated by Django 3.0.5 on 2024-05-27 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0032_auto_20240527_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdetails',
            name='patient',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
