# Generated by Django 3.0.5 on 2024-05-27 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0033_auto_20240527_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='doctorName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hospitalName',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientName',
        ),
    ]
