# Generated by Django 3.0.5 on 2024-05-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0034_auto_20240527_1816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientdetails',
            old_name='patient',
            new_name='appointmentId',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='appointment',
        ),
        migrations.AddField(
            model_name='patientdetails',
            name='patientID',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointmentId',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
