# Generated by Django 3.0.5 on 2024-05-30 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0035_auto_20240527_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='appointmentDate',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='diagnosis',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='symptoms',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='patientdischargedetails',
            name='patientName',
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='diagnosis',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='symptoms',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='patientdischargedetails',
            name='treatment',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
