# Generated by Django 3.0.5 on 2024-06-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0036_auto_20240601_0501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='hospitalId',
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctorName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientName',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
