# Generated by Django 3.0.5 on 2024-05-30 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0036_auto_20240530_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
