# Generated by Django 3.0.5 on 2024-05-30 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0037_appointment_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
