# Generated by Django 3.0.5 on 2024-06-02 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0038_auto_20240602_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointmentDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
