# Generated by Django 3.0.5 on 2024-05-30 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0038_auto_20240530_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='timestamp',
        ),
    ]
