# Generated by Django 3.0.5 on 2024-06-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0039_auto_20240602_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='datestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
