# Generated by Django 3.0.5 on 2024-06-08 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0040_appointment_datestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPharmacy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacyId', models.PositiveIntegerField(null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/AdminPharmacyProfilePic/')),
                ('address', models.CharField(max_length=40)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.PositiveIntegerField(null=True)),
                ('message', models.TextField(max_length=500, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='PharmacyMedicine',
            new_name='PharmacyInventory',
        ),
        migrations.DeleteModel(
            name='PatientDischargeDetails',
        ),
    ]
