# Generated by Django 3.0.5 on 2024-06-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0043_auto_20240612_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdetailsadmin',
            name='appointmentId',
        ),
        migrations.RemoveField(
            model_name='patientdetailsadmin',
            name='patientID',
        ),
    ]
