# Generated by Django 3.0.5 on 2024-06-12 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0049_auto_20240612_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='description',
            new_name='dosageInstruction',
        ),
        migrations.AddField(
            model_name='prescription',
            name='sideEffects',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Cardiology', 'Cardiology'), ('Dermatology', 'Dermatology'), ('Emergency Medicine', 'Emergency Medicine'), ('Allergy and Immunology', 'Allergy and Immunology'), ('Endocrinology', 'Endocrinology'), ('Gastroenterology', 'Gastroenterology'), ('Hematology', 'Hematology'), ('Infectious Disease', 'Infectious Disease'), ('Nephrology', 'Nephrology'), ('Neurology', 'Neurology'), ('Oncology', 'Oncology'), ('Pediatrics', 'Pediatrics'), ('Psychiatry', 'Psychiatry'), ('Pulmonology', 'Pulmonology'), ('Rheumatology', 'Rheumatology')], default='Cardiologist', max_length=50),
        ),
    ]
