# Generated by Django 3.0.5 on 2024-06-13 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0050_auto_20240612_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='datestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='eth_address',
            field=models.CharField(max_length=42, null=True),
        ),
    ]
