# Generated by Django 3.0.5 on 2024-06-15 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0052_remove_prescription_eth_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dosageInstruction',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
