# Generated by Django 3.0.5 on 2024-06-17 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0053_auto_20240615_1407'),
        ('hospital', '0053_auto_20240615_1440'),
    ]

    operations = [
    ]
